apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: validator4-pvc
  namespace: besu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
