apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-backups-pvc
  namespace: besu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
