apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-scaler-binding
  namespace: besu
subjects:
  - kind: ServiceAccount
    name: default
    namespace: besu
roleRef:
  kind: Role
  name: statefulset-scaler
  apiGroup: rbac.authorization.k8s.io
