apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu-ops
  namespace: besu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: besu-ops
  template:
    metadata:
      labels:
        app: besu-ops
    spec:
      containers:
        - name: besu-ops
          image: kindservices/besu-ops:0.0.16
          ports:
            - containerPort: 3000
          env:
            - name: DATA_DIR
              value: /data
            - name: BACKUP_DIR
              value: /backups
          volumeMounts:
            - name: validator1-data
              mountPath: /data/besu-validator1
              readOnly: false
            - name: validator2-data
              mountPath: /data/besu-validator2
              readOnly: false
            - name: validator3-data
              mountPath: /data/besu-validator3
              readOnly: false
            - name: validator4-data
              mountPath: /data/besu-validator4
              readOnly: false
            - name: backups
              mountPath: /backups
      volumes:
        - name: validator1-data
          persistentVolumeClaim:
            claimName: validator1-pvc
        - name: validator2-data
          persistentVolumeClaim:
            claimName: validator2-pvc
        - name: validator3-data
          persistentVolumeClaim:
            claimName: validator3-pvc
        - name: validator4-data
          persistentVolumeClaim:
            claimName: validator4-pvc
        - name: backups
          persistentVolumeClaim:
            claimName: besu-backups-pvc
