apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: member3-data-pvc
  namespace: quorum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
